[server]
maxUploadSize = 2000 #MB
maxMessageSize = 1500 #MB
# enableXsrfProtection = false   # TEMPORARY for debugging
# enableCORS = false             # TEMPORARY for debugging

[theme]
base = "light"                 
